# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import vehicle_pb2 as vehicle__pb2

GRPC_GENERATED_VERSION = '1.75.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in vehicle_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class VehicleServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ProcessVideo = channel.unary_stream(
                '/vehicle.VehicleService/ProcessVideo',
                request_serializer=vehicle__pb2.ProcessVideoRequest.SerializeToString,
                response_deserializer=vehicle__pb2.ProcessUpdate.FromString,
                _registered_method=True)
        self.ProcessWebcam = channel.unary_stream(
                '/vehicle.VehicleService/ProcessWebcam',
                request_serializer=vehicle__pb2.ProcessWebcamRequest.SerializeToString,
                response_deserializer=vehicle__pb2.ProcessUpdate.FromString,
                _registered_method=True)


class VehicleServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def ProcessVideo(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ProcessWebcam(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_VehicleServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ProcessVideo': grpc.unary_stream_rpc_method_handler(
                    servicer.ProcessVideo,
                    request_deserializer=vehicle__pb2.ProcessVideoRequest.FromString,
                    response_serializer=vehicle__pb2.ProcessUpdate.SerializeToString,
            ),
            'ProcessWebcam': grpc.unary_stream_rpc_method_handler(
                    servicer.ProcessWebcam,
                    request_deserializer=vehicle__pb2.ProcessWebcamRequest.FromString,
                    response_serializer=vehicle__pb2.ProcessUpdate.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'vehicle.VehicleService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('vehicle.VehicleService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class VehicleService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ProcessVideo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/vehicle.VehicleService/ProcessVideo',
            vehicle__pb2.ProcessVideoRequest.SerializeToString,
            vehicle__pb2.ProcessUpdate.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ProcessWebcam(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/vehicle.VehicleService/ProcessWebcam',
            vehicle__pb2.ProcessWebcamRequest.SerializeToString,
            vehicle__pb2.ProcessUpdate.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
