# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: vehicle.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'vehicle.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rvehicle.proto\x12\x07vehicle\"\xfc\x01\n\x0c\x41ppConfigMsg\x12\x12\n\nmodel_name\x18\x01 \x01(\t\x12\x0c\n\x04\x63onf\x18\x02 \x01(\x02\x12\x0b\n\x03iou\x18\x03 \x01(\x02\x12\x0e\n\x06\x64\x65vice\x18\x04 \x01(\t\x12\x18\n\x10line_orientation\x18\x05 \x01(\t\x12\x15\n\rline_position\x18\x06 \x01(\x02\x12\x18\n\x10invert_direction\x18\x07 \x01(\x08\x12\x14\n\x0c\x63\x61pacity_car\x18\x08 \x01(\x05\x12\x15\n\rcapacity_moto\x18\t \x01(\x05\x12\x12\n\nenable_csv\x18\n \x01(\x08\x12\x0f\n\x07\x63sv_dir\x18\x0b \x01(\t\x12\x10\n\x08\x63sv_name\x18\x0c \x01(\t\"g\n\x13ProcessVideoRequest\x12\x12\n\nvideo_path\x18\x01 \x01(\t\x12%\n\x06\x63onfig\x18\x02 \x01(\x0b\x32\x15.vehicle.AppConfigMsg\x12\x15\n\rstream_frames\x18\x03 \x01(\x08\"d\n\x14ProcessWebcamRequest\x12\x0e\n\x06\x63\x61m_id\x18\x01 \x01(\x05\x12%\n\x06\x63onfig\x18\x02 \x01(\x0b\x32\x15.vehicle.AppConfigMsg\x12\x15\n\rstream_frames\x18\x03 \x01(\x08\"d\n\rProcessUpdate\x12\x10\n\x08progress\x18\x01 \x01(\x02\x12\x12\n\nframe_jpeg\x18\x02 \x01(\x0c\x12\x10\n\x08\x63sv_path\x18\x03 \x01(\t\x12\r\n\x05\x65rror\x18\x04 \x01(\t\x12\x0c\n\x04\x64one\x18\x05 \x01(\x08\x32\xa2\x01\n\x0eVehicleService\x12\x46\n\x0cProcessVideo\x12\x1c.vehicle.ProcessVideoRequest\x1a\x16.vehicle.ProcessUpdate0\x01\x12H\n\rProcessWebcam\x12\x1d.vehicle.ProcessWebcamRequest\x1a\x16.vehicle.ProcessUpdate0\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'vehicle_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_APPCONFIGMSG']._serialized_start=27
  _globals['_APPCONFIGMSG']._serialized_end=279
  _globals['_PROCESSVIDEOREQUEST']._serialized_start=281
  _globals['_PROCESSVIDEOREQUEST']._serialized_end=384
  _globals['_PROCESSWEBCAMREQUEST']._serialized_start=386
  _globals['_PROCESSWEBCAMREQUEST']._serialized_end=486
  _globals['_PROCESSUPDATE']._serialized_start=488
  _globals['_PROCESSUPDATE']._serialized_end=588
  _globals['_VEHICLESERVICE']._serialized_start=591
  _globals['_VEHICLESERVICE']._serialized_end=753
# @@protoc_insertion_point(module_scope)
